#!/bin/bash

eval `xdotool getmouselocation --shell`
echo $X $Y > /tmp/$$

xdotool search --onlyvisible --desktop `xdotool get_desktop` --name '' | while read line; do 
    PROP=`xprop -id $line _NET_WM_STATE`
    [[ $PROP =~ MAXIMIZED ]] || {
        eval $(xwininfo -id $line -all | \
            perl -ne '
if (/Corners:\s*\+([0-9]*)\+([0-9]*)/) { print "sx=$1;sy=$2;" }
if (/Width:\s*([0-9]*)/) { print "width=$1;" }
if (/Height:\s*([0-9]*)/) { print "height=$1;" }
if (/Frame extents:\s*([0-9]*),\s*([0-9]*),\s*([0-9]*),\s*([0-9]*)/) { print "fl=$1;fr=$2;fu=$3;fd=$4;" }
')
        echo $line $(( $sx - $fl )) $(( $sy - $fu )) $(( $width + $fl + $fr )) $(( $height + $fu + $fd ))
    }
done >> /tmp/$$

WINDOW=`cat /tmp/$$ | osd_box_sel -h`
if [ -n "$WINDOW" ]; then
    xdotool windowfocus --sync $WINDOW windowraise $WINDOW
fi
rm /tmp/$$
